[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
upload_port = COM5
monitor_port = COM5
lib_deps =
    adafruit/Adafruit INA219@^1.2.3
    madhephaestus/ESP32Servo@^3.2.1
