[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
lib_deps =
    madhephaestus/ESP32Servo@^3.2.1
